---
title: "889test"
output: html_document
---

```{r setup, include=FALSE}
library("rjson")
```


```{r}
result <- fromJSON(file = "FS_P1_Traditional(2).json")
test <-result[[1]]
test_number <- length(test)
test_number
```


```{r}
task_number <- 0
for (tasks in test) {
  not_over <- TRUE
  over_distance <- 0
  task_number <- task_number + 1
  task_time <- tasks$endTime - tasks$startTime
  plot(tasks$moveTraceTime,tasks$moveTrace,ylim = rev(c(1,tasks$documentHeight)),type="b",pch = 16,cex=0.5)
  overshoot_position <- c()
  if(tasks$startPosition > tasks$targetPosition){
    #scroll up
    overshoot_point <- tasks$targetPosition - tasks$windowHeight
    secondary_overshoot_point <- tasks$targetPosition + 400
    over_position <- 0
    for (position in tasks$moveTrace) {
      if (position <= overshoot_point){
        #overshoot
        if (over_distance < abs(position - overshoot_point)){
          over_distance <- abs(position - overshoot_point)
          over_position <- position
        }
        not_over <- FALSE
      } 
      if(position > overshoot_point & (! not_over)){
        not_over <- TRUE
        overshoot_position <- c(overshoot_position, over_position)
      }
    }
  } else {
    #scroll down
    overshoot_point <- tasks$targetPosition + 400
    secondary_overshoot_point <- tasks$targetPosition - tasks$windowHeight
    over_position <- 0
    for (position in tasks$moveTrace) {
      if (position >= overshoot_point & not_over){
        #overshoot
        if (over_distance < abs(position - overshoot_point)){
          over_distance <- abs(position - overshoot_point)
          over_position <- position
        }
        not_over <- FALSE
      }
      if(position < overshoot_point & (! not_over)){
        not_over <- TRUE
        overshoot_position <- c(overshoot_position, over_position)
      }
    }
  }
  
  over_distance_array <- abs(overshoot_position - overshoot_point)
  total_overshoot <- sum(over_distance_array)
  
  abline(h=tasks$targetPosition, col="green")
  abline(h=tasks$chapterLocation, col="blue")
  abline(h=overshoot_point, col="red")
  abline(h=secondary_overshoot_point, col="red")
  #abline(h=overshoot_position, col="black")
  cat("Task number", task_number)
  cat("\nTask completation time: ", task_time)
  cat("\nStarting position: ", tasks$startPosition)
  cat("\nTarget position: ", tasks$targetPosition)
  cat("\nOvershoot point: ", overshoot_point)
  cat("\nOvershoot positions: ", overshoot_position)
  cat("\nAmount of overshoot: ", length(overshoot_position))
  cat("\n---------------------------------------------------------------\n")
}
```



